[package]
name = "basic_router"
version = "0.1.0"
authors = ["Bradley Beddoes <bradleybeddoes@gmail.com>",
           "Shaun Mangelsdorf <s.mangelsdorf@gmail.com>"]
description = "An example of the Gotham Router showing usage of HTTP verbs such as Get and Post."
license = "MIT/Apache-2.0"
readme = "README.md"
publish = false

[dependencies]
gotham = { path = "../../../gotham" }
gotham_derive = { path = "../../../gotham_derive" }

hyper = "0.11"
futures = "~0.1.11"
mime = "0.3"
log = "0.3"
